# Generated by Django 4.0.3 on 2023-04-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_pr',
            field=models.BooleanField(default=False),
        ),
    ]
